### ISSUE TITLE
Hello I have a problem when I try to install the script on qbcore I get an error

### ISSUE THREAD

**Issue by Mochcin** [zRxnx/zrx_lobby#1]
Hello
I have a problem when I try to install the script on qbcore I get an error

[  script:zrx_utility] SCRIPT ERROR: @zrx_utility/server/server.lua:10: attempt to index a nil value (global 'BRIDGE')
[  script:zrx_utility] > ref (@zrx_utility/server/server.lua:10)
[  script:zrx_utility] > fn (@zrx_lobby/server/server.lua:2)
[    script:zrx_lobby] SCRIPT ERROR: @zrx_lobby/server/server.lua:2: 
[    script:zrx_lobby]  An error occurred while calling export `GetUtility` in resource `zrx_utility`:
[    script:zrx_lobby] 
[    script:zrx_lobby]  ---
[           resources] Started resource zrx_lobby

I have already tried to use ox as a bridge and convert qbx to qbcore but I always get this error, I even tried to make a clean server on qbx and I also got it

**Comment by zRxnx** [comment]
qbcore isnt supported by the bridge yet
