### ISSUE TITLE
disable the lobby from appearing when entering the server,

### ISSUE THREAD

**Issue by Mochcin** [zRxnx/zrx_lobby#2]
Hello
When I disable the lobby from appearing when entering the server, I receive this error

[    script:zrx_lobby] SCRIPT ERROR: @zrx_lobby/server/server.lua:337: attempt to index a nil value (local 'lobbyData')
[    script:zrx_lobby] > callbackResponse (@ox_lib/imports/callback/server.lua:60)
[    script:zrx_lobby] > handler (@ox_lib/imports/callback/server.lua:76)
[    script:zrx_lobby] 

[   2549437] [b2944_GTAProce]             MainThrd/ ^1SCRIPT ERROR: citizen:/scripting/lua/scheduler.lua:739: ^1SCRIPT ERROR: @zrx_lobby/client/functions.lua:141: attempt to index a nil value (local 'LOBBY_DATA')^7
[   2549437] [b2944_GTAProce]             MainThrd/ ^3> OpenMainMenu^7 (^5@zrx_lobby/client/functions.lua^7:141)
[   2549437] [b2944_GTAProce]             MainThrd/ ^3> ref^7 (^5@zrx_lobby/client/client.lua^7:6)
[   2549437] [b2944_GTAProce]             MainThrd/ ^7

**Comment by Mochcin** [comment]
I use new esx

**Comment by zRxnx** [comment]
Fixed in the new versions
